apiVersion: apps/v1
kind: Deployment # This manifest is a deployment
metadata:
  name: main
spec:
  replicas: 1 # Only a single replica of the main pod
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main 
          image: felixgroup/main:latest # The image to be run in the pod
          volumeMounts: # Mount a volume inside the container
            - name: output-volume
              mountPath: /app/output
      volumes: # Define a volume and bind it to the PVC
        - name: output-volume
          persistentVolumeClaim:
            claimName: output-pvc
