apiVersion: apps/v1
kind: Deployment # Deloyment for the webserver running via nginx
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: nginx # Name of the container in the pod
          image: nginx:latest # Name of the image (default latest nginx image)
          ports:
            - containerPort: 80 # Expose the port to the container
          volumeMounts:
            - name: output-volume
              mountPath: /usr/share/nginx/html
      volumes: # Bind a volume to the PVC
        - name: output-volume
          persistentVolumeClaim:
            claimName: output-pvc
